### ISSUE TITLE
IE and supported versions of Windows

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1846]
Was looking at this a bit today, and it seems that browscap has more Windows versions defined for different versions of IE than are supported by the operating systems themselves. For example, I was testing loading IE 9.0 on Windows XP today, which isn't possible (not possible to download from MS, if you can get an EXE from another source, it doesn't install on XP).

I looked around a bit for the official support of IE across different versions of Windows, and found this doc: https://support.microsoft.com/en-us/help/11531/internet-explorer-system-requirements

I also googled around a bit for some other cases (like is it possible to install anything > IE 6.0 on Windows 2000) and found various support articles with answers from MS reps (or community moderators) that suggest it isn't possible to mix IE X.0 with Windows X. Ultimately I came to this conclusion:

## IE 6.0
This isn't in that linked document, but using wikipedia article (https://en.wikipedia.org/wiki/Internet_Explorer_6) and other searches on the web, this is what I've come up with:
 - Windows XP and lower only (Win98, NT, Win2000, WinME)
 - **Maybe** Windows 7 in XP Mode (I haven't tried to confirm this yet, XP mode may show itself as XP in the UA, but maybe it shows Windows 7)

### to-do
 - [ ] Remove Windows 8
 - [ ] Remove Vista
 - [ ] Add Windows 98
 - [x] Test Windows 7
 - [ ] Remove Windows 7

## IE 7.0
Also not in that MS document, but wikipedia (https://en.wikipedia.org/wiki/Internet_Explorer_7) and related searches.
 - Windows XP and Windows Vista only
 - **Maybe** Windows 7 in XP Mode (same considerations as IE 6.0)

### to-do
 - [ ] Remove Windows 8
 - [ ] Remove Windows 2000
 - [x] Test Windows 7
 - [ ] Remove Windows 7

## IE 8.0
 - Windows XP
 - Windows Vista
 - Windows 7

### to-do
 - [ ] Remove Windows 8

## IE 9.0
 - Windows Vista
 - Windows 7

### to-do
 - [ ] Remove Windows 8
 - [ ] Remove Windows XP

## IE 10.0
 - Windows 7
 - Windows 8

### to-do
 - [ ] Remove Windows XP
 - [ ] Remove Windows 8.1
 - [ ] Remove Windows 10

## IE 11.0
 - Windows 7
 - Windows 8.1 (yes, just 8.1, not 8.0. Apparently not possible to install IE 11 on 8.0 systems)
 - Windows 10

### to-do
 - [ ] Remove Windows XP
 - [ ] Remove Windows 8
 - [ ] Remove Windows Vista

I'll make these changes and see what tests fail and report back.

**Comment by jaydiablo** [comment]
So "XP Mode" in Windows 7 is just a virtual machine running in Microsoft's Virtual PC app.

I couldn't get it to run, as it doesn't seem to like running Virtual PC inside a Virtual Box copy of Windows 7, but I don't see why it would report as Windows 7 when it's really a Windows XP VM.

**Comment by jaydiablo** [comment]
There were only 6 failures when I removed all of the Windows versions in that list:

```
Mozilla/5.0 (compatible; MSIE 10.0; Trident/6.0; Windows NT 5.0; FDM; Zango 2.6.91; Zango 5.3.98)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/6.0)
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.2; 360SE; ; 11sungb_AAPF0A95321C6D)
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.2; Win64; x64; Trident/5.0)
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; Win64; x64; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727)
```

I think it's fine to move these to the invalid versions test file and remove these versions of Windows as described.

Objections?

**Comment by mimmi20** [comment]
No objections.
